# Generated by Django 4.0.6 on 2022-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasemachine',
            name='exams',
            field=models.CharField(default='', max_length=10),
        ),
    ]
