# Generated by Django 4.0.6 on 2022-10-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_releasemachine_exams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasemachine',
            old_name='exams',
            new_name='examA',
        ),
        migrations.AddField(
            model_name='releasemachine',
            name='examB',
            field=models.CharField(default='', max_length=10),
        ),
    ]
